# Generated by Django 4.1.1 on 2022-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
            ],
        ),
    ]
